"""Add club_messages table

Revision ID: 9aecdecb9328
Revises: 8c756268a1ae
Create Date: 2024-12-30 14:59:02.044716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9aecdecb9328'
down_revision = '8c756268a1ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('club_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=25), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('club_members', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
